### ISSUE TITLE
The version of bower components (bower.json)

### ISSUE THREAD

**Issue by highdev2016** [AlexanderMac/mean-starter#1]
Hello,

I think the version of bower components are old now.
I cloned your project and built a new environment a few days ago, but it is not working correctly on my local.
So I have changed the version of bower components, and it is working fine now.

**Comment by highdev2016** [comment]
"dependencies": {
    "angular": "~1.6.x",
    "angular-resource": "~1.6.x",
    "angular-route": "~1.6.x",
    "angular-bootstrap": "^2.1.3",
    "bootstrap": "~3.3.4",
    "lodash": "~3.10.1",
    "SpinKit": "spinkit#^1.2.5",
    "toastr": "^2.1.3"
  },
  "resolutions": {
    "angular": "~1.6.x"
  },

I modified the bower.json like above.

**Comment by AlexanderMac** [comment]
Hi, I've removed `resolutions` section from bower.json, so now bower will install the latest available versions of the modules with the same major number.
